name: roamlust
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # SVG画像を表示するためのパッケージです
  flutter_svg: ^2.0.10
  http: ^1.6.0
  intl: ^0.20.2
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true

  # ここに登録したフォルダ内のファイルは、PWA起動時に一括でダウンロードされます
  assets:
    - assets/json/countries_master.json
    - assets/json/rankings/
    - assets/json/wikipedia/
    - assets/json/restcountries/
    - assets/flags/
    - assets/logo.svg
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_size: 21 # Androidの仕様対策
  web:
    generate: true
    image_path: "assets/icon.png"